var config_basepath = "http://117.71.25.104:81/bytuetechAPI/static_data/";
var config_jsDetailPath= "js/data/detail/";
var config_jsCategoryPath = "js/data/categorylist/";
var config_jsContentPath = "js/data/programlist/";
var config_jsChannelPath = "js/data/channellist/";
var config_jsADPath = "js/data/ad/";
var config_moviebasecategoryid = "1001";
var config_seriesbasecategoryid = "1002,1005";
var config_varietybasecategoryid = "1003,1004";